### PR TITLE
reactive retrofit instead of volley

### LINKED ISSUE #44: io.reactivex.rxjava3.exceptions.UndeliverableException
Play Store Release 1.3.2
Android 10, Samsung Galaxy S9+

```
io.reactivex.rxjava3.exceptions.UndeliverableException: 
  at io.reactivex.rxjava3.plugins.RxJavaPlugins.onError (RxJavaPlugins.java:367)
  at io.reactivex.rxjava3.subjects.ReplaySubject.onError (ReplaySubject.java:373)
  at org.tosl.coronawarncompanion.dkdownload.-$$Lambda$H3l_4TOAnevR-vcMNir9nCKfoFA.onErrorResponse (Unknown Source:2)
  at com.android.volley.Request.deliverError (Request.java:617)
  at com.android.volley.ExecutorDelivery$ResponseDeliveryRunnable.run (ExecutorDelivery.java:104)
  at android.os.Handler.handleCallback (Handler.java:883)
  at android.os.Handler.dispatchMessage (Handler.java:100)
  at android.os.Looper.loop (Looper.java:237)
  at android.app.ActivityThread.main (ActivityThread.java:8125)
  at java.lang.reflect.Method.invoke (Native Method)
  at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run (RuntimeInit.java:496)
  at com.android.internal.os.ZygoteInit.main (ZygoteInit.java:1100)
Caused by: com.android.volley.TimeoutError: 
  at com.android.volley.toolbox.BasicNetwork.performRequest (BasicNetwork.java:173)
  at com.android.volley.NetworkDispatcher.processRequest (NetworkDispatcher.java:131)
  at com.android.volley.NetworkDispatcher.processRequest (NetworkDispatcher.java:111)
  at com.android.volley.NetworkDispatcher.run (NetworkDispatcher.java:90)
```

@kbobrowski Any idea on this one?

### PR DESCRIPTION
**Pull request by kbobrowski**
fix #44 

todo:
- [x] Switzerland
- [x] Germany
- [x] Poland
- [x] Austria

### CODE REVIEW

**Comment by kbobrowski** [comment]
We have to account for 404 errors as something normal, e.g. in querying `/date/{currentDate}/hour` when it's not available yet.

Currently all HTTP errors are [silently ignored](https://github.com/kbobrowski/corona-warn-companion-android-1/blob/4e3e901c8efe75173af163a0cfbb4d1457138e62/corona-warn-companion/src/main/java/org/tosl/coronawarncompanion/dkdownload/DKDownloadUtils.java#L30) which may be a good thing since if one query is failing then all other queries would be still processed. But it also may hide some problems with wrong URL in case of API change. @mh- what would be your preferred way of handling this? Maybe some toast / notification can be displayed to the user in case of HTTP error, and possibly also included in Play Store analytics

**Comment by mh-** [comment]
Is the retrofit timeout shorter than the previous Volley timeout?

**Comment by kbobrowski** [comment]
Looks like volley has default timeout of 2.5 seconds, and retrofit is using OkHttpClient, which by default should have the timeout of 10 seconds

**Comment by mh-** [comment]
I tried the _new_ setup (with a slow network connection) and **got some timeout toasts** (at least 2) - 
then I ran the _old_ setup on the same device and got more downloaded keys (presumably all available keys):

_New_:
wac_new

_Old_:
wac_old

That's why I assumed that the new setup has a shorter timeout.
I need to further look into this.

**Comment by mh-** [comment]
Well, probably coincidence. Anyway, it would be good to have the option to set the okhttp timeout to a longer value.

I think I will add a counting mechanism to the timeouts - i.e. display the toast, and increase a counter - 
and then display this as a warning in the text, like "x Downloaded Keys. (Warning: n download timeouts.)".

**Comment by kbobrowski** [comment]
Longer timeouts can be configured now here: https://github.com/mh-/corona-warn-companion-android/pull/45/commits/3a161dccf7c45b8d0e3fe9508e3d6a2d7fedeb44#diff-295c469ec9de8638d5a36d2ca0190bf3R121-R125

Providing a user with some summary information how the whole download process went would be nice :)

**Review by mh- — APPROVED** [review]

**Pull request merged**
