### PR TITLE
Location

### PR DESCRIPTION
**Pull request by uhengart**
Display the location of an exposure on a map using the osmdroid framework.

### CODE REVIEW

**Comment by mh-** [comment]
Hi @uhengart 

Thank you for your contribution. 
However, I'm not sure how to proceed with this. The thing is, I'd rather not include location information in the app that I distribute. The main reason is that I do not want to make this app appear as if it would easily be used to identify infected persons (cf. #73).

Cheers,
Michael

**Comment by mh-** [comment]
Then again, this PR takes location info only from RaMBLE; and users who have RaMBLE installed can also look the location up in their RaMBLE history, so from a privacy perspective (the privacy of the users who reported their COVID-19 infection), this PR doesn't make much of a difference.

**Review by mh- — APPROVED** [review]
After some re-consideration, I'm now convinced that this feature will not affect privacy, and I think it makes sense to add this. 
@uhengart Thanks a lot for the implementation!

**Comment by uhengart** [comment]
Thanks for accepting the PR.  

I agree that showing a map with the location of an exposure to a user does not give more information to the user user than the user already has access to (at least for technically savvy users).

Your additional commit, getting the user's approval before accessing the OpenStreetMap server, is a good idea. I am adding a discussion of the underlying privacy issue here so that there is a formal record.

The OpenStreetMap server obviously sees the requests for map tiles from the app. Therefore, the OpenStreetMap server can infer that somebody at this location has COVID-19 or was exposed to COVID-19. For some locations, like a shopping mall, a restaurant, or an apartment building, inferring the identity of the infected or exposed users would be hard. For others, like a single-family home, it would be easier. However, the zoom level of the map is chosen to typically cover many houses so there is some uncertainty.

The Corona-Warn App (and Canada's COVID Alert app) have a similar, more severe privacy vulnerability: The server that receives the diagnosis keys upon an infection learns the IP address of the infected user. In Canada's case, Amazon hosts this server and could infer the identity of the infected user user if the user recently shopped with Amazon. Germany has given this vulnerability a medium rating in its risk analysis and it may be addressed in a future update. Canada has taken a similar position.

Given this reasoning and keeping in mind that the OpenStreetMap vulnerability is harder to take advantage of than the diagnosis keys upload vulnerability, there is a valid argument to be made not to add an additional defense against the OpenStreetMap vulnerability (other than getting the user's approval before accessing the OpenStreetMap server). That said, I would certainly be willing to add an additional defense, like sending dummy tile requests to the server, to the code base if there is consensus that this is needed.

**Pull request merged**
