### PR TITLE
added England and Wales

### PR DESCRIPTION
**Pull request by kbobrowski**
@benjeffery I think you've went through the UK download logic once, I think this should be ok but you might want to double-check

### CODE REVIEW

**Comment by kbobrowski** [comment]
this should probably be only "England and Wales", as Scotland and Northern Ireland seem to have different apps

**Comment by benjeffery** [comment]
> this should probably be only "England and Wales", as Scotland and Northern Ireland seem to have different apps

That's right, annoying there isn't a country code for "England and Wales" the nearest thing is GB-EAW in ISO 3166-2. No flag either. Might be best two have two entries one for England and one for Wales?

**Comment by kbobrowski** [comment]
I put England and Wales into one entry with flags next to each other, two separate entries may lead to double download of DKs. We don't display country code anywhere, it's just for keeping track of the state, so just put EAW there

**Review by benjeffery — APPROVED** [review]
LGTM on a quick check. Thanks @kbobrowski I'll be using this for sure.

**Review by mh- — APPROVED** [review]
Thank you!

**Pull request merged**
