### PR TITLE
Support for multiple countries

### PR DESCRIPTION
**Pull request by kbobrowski**
This is introducing major refactoring of DK download logic, which would make writing country-specific download code easy as just one interface would need to be implemented, just an idea :)

Builds on #23 as otherwise the project did not compile on Linux

Related to #12

### CODE REVIEW

**Comment by pdehaye** [comment]
Looks good! Which country is next? Seems Austria is logical target. 

You can find information [here](https://github.com/sftcd/tek_transparency/blob/5c226914a0d8010e567b69884b5d3f127a63e060/tek_survey.sh#L651) on how to download their keys, as well as other countries'.

**Comment by kbobrowski** [comment]
Yes Austria is also on my list, but beyond that I probably won't be able to follow changes on backend APIs, would be good to bring onboard developers from specific countries

**Comment by mh-** [comment]
How many DKs should we expect in Switzerland and Poland?
The current mechanism yields only 193 in Switzerland (around 13..19 per day)
and 36 in Poland (around 3..4 per day). And the Swiss curve looks surprisingly flat.
Apparently they don't see a need for padding?

Do you know of reference values that we could check, like https://micb25.github.io/dka/ ?

**Comment by pdehaye** [comment]
This is definitely wrong, @mh- 

For CH, how many you see should depend on how far back you are looking. Expect ~30 per day produced each day. So the most recent file should have 0-30, the second most recent 30-60, the third 60-90, etc. For 14 days. So a lot lot more (lower bound: 30*14*13/2 = 2730).
The companion app would need to do 14 downloads of files at URLs https://down.dsg.cs.tcd.ie/tact/tek-counts/{Unix timestamp in ms at midnight}, each reflecting the counts given just before. 

For Poland, I don't know the system well, but that looks more correct.

See https://down.dsg.cs.tcd.ie/tact/tek-counts/ for direction.

**Pull request merged**
